### ISSUE TITLE
Create collections of events

### ISSUE THREAD

**Issue by madb1lly** [tim-hellhake/cron-adapter#2]
Hi @tim-hellhake,

At present each cron event exists in isolation and is created as a separate Thing on the UI. This may be fine for events which don't have any relation to any other time-based events, but when a set of events belong together then it makes the Things page very overcrowded.

For example, I have created 8 events for controlling my heaters at different times during a normal week. 4 events turn the heaters on and 4 turn them off.

An improvement to the Cron add-on would be to allow all 4 On events to be grouped together so that they all appear as one Thing on the Things page. Same for the 4 Off events.

Even better would be to associate On and Off events into pairs so that they create True and False periods which can then be used as inputs to rules rather than the base Cron events. Pairs of On/Off events could be grouped as above so instead of having a Thing for On events and a Thing for Off events there would just be one Thing for On/Off periods. However, I realise that this last paragraph moves away from Cron syntax and is more like a timer, so may not be appropriate for this add-on.

Cheers :)

**Comment by tim-hellhake** [comment]
I see your problem.
I'm adding groups of cron jobs.
The hardest part is to migrate from the old config format to the new one without breaking existing cron job definitions.

**Comment by tim-hellhake** [comment]
The new update is out :)

> Even better would be to associate On and Off events into pairs so that they create True and False periods which can then be used as inputs to rules rather than the base Cron events

I agree, but I think a dedicated addon for this would be a better option.
I'm closing this now as there is already an issue for this:

https://github.com/mozilla-iot/gateway/issues/2347

If you have any problems with the update, please let me now.
