### ISSUE TITLE
Rule triggers not firing

### ISSUE THREAD

**Issue by chasingmaxwell** [tim-hellhake/cron-adapter#3]
I've enabled this add-on and tried a number of different cron expressions:

- `0 6 * * *` -> 6am every day
- `0 21 * * *` -> 9pm every day
- `0 2 * * *` -> 2am every day
- `0 * * * * *` -> every minute

But none of the rules I've created with cron triggers are firing. Am I doing something wrong? I have zigbee lights and slack both configured to respond to these cron triggers. Nothing seems to work.

**Comment by tim-hellhake** [comment]
Hi @chasingmaxwell 😬

> Am I doing something wrong?

The expressions seem to be fine.
Are there any errors in the log?

**Comment by tim-hellhake** [comment]
I just installed it on a brand new gateway and had an error in the log.
There seem to be something wrong with the config.

**Comment by tim-hellhake** [comment]
Found it!
My test rule is now successfully skipping to the next track of my Spotify playlist every second 😆.

**Comment by tim-hellhake** [comment]
I never experienced the bug because the migration script converted my old config.
For new configs, the wrong event was fired.

**Comment by chasingmaxwell** [comment]
Thanks again for the quick response and fix (during the weekend too!)

I'll pull the update down once it's available and report back.

**Comment by chasingmaxwell** [comment]
This is working now!
