### ISSUE TITLE
Jobs are one hour off

### ISSUE THREAD

**Issue by stutrek** [tim-hellhake/cron-adapter#4]
My cron jobs are running one hour too early. Presently we're in daylight savings, which could be the cause.

My sanity checks:

- Time zone is correct in the cron addon
- Time zone is correct on the computer (macOS)

<img width="887" alt="image" src="https://user-images.githubusercontent.com/339327/83222024-5fc85000-a145-11ea-9792-01b7b7d65efc.png">

EDIT: 
It looks like it's caused by this. 😞 node-cron/tz-offset#11

EDIT2:
I no longer know what's happening. My job for `0 */3 * * *` ran at 1.

**Comment by stutrek** [comment]
It looks like it's caused by this. 😞 

https://github.com/node-cron/tz-offset/pull/11

**Comment by tim-hellhake** [comment]
It looks like `node-cron` is dead.
The fix will probably not be merged.
I replaced it with `cron`, which seems to use a proper timezone library (moment timezone).

**Comment by tim-hellhake** [comment]
First of all, thanks for the report @stutrek.
It looks like `node-cron` is dead.
The fix will probably not be merged.
I replaced it with `cron`, which seems to use a proper timezone library (moment timezone).

**Comment by tim-hellhake** [comment]
As soon as the PR is merged you can test it :)

**Comment by stutrek** [comment]
Thank you! My gateway pulled the update and my plants are getting watered at the right time now.
